; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.30501.0 

	TITLE	C:\Users\Simon\Documents\GitHub\Game-of-Life\TextureManager.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

PUBLIC	?MAX_TEXTURES@CTextureManager@@0HB		; CTextureManager::MAX_TEXTURES
PUBLIC	?MAX_NAME_LENGTH@CTextureManager@@0HB		; CTextureManager::MAX_NAME_LENGTH
;	COMDAT ?MAX_NAME_LENGTH@CTextureManager@@0HB
CONST	SEGMENT
?MAX_NAME_LENGTH@CTextureManager@@0HB DD 032H		; CTextureManager::MAX_NAME_LENGTH
CONST	ENDS
;	COMDAT ?MAX_TEXTURES@CTextureManager@@0HB
CONST	SEGMENT
?MAX_TEXTURES@CTextureManager@@0HB DD 064H		; CTextureManager::MAX_TEXTURES
CONST	ENDS
PUBLIC	?LoadTexture@CTextureManager@@QAEPAUID3D10ShaderResourceView@@QAD@Z ; CTextureManager::LoadTexture
PUBLIC	?UnloadTexture@CTextureManager@@QAEXQAD@Z	; CTextureManager::UnloadTexture
PUBLIC	?UnloadTexture@CTextureManager@@QAEXH@Z		; CTextureManager::UnloadTexture
PUBLIC	??0CTextureManager@@QAE@PAUID3D10Device@@@Z	; CTextureManager::CTextureManager
PUBLIC	??1CTextureManager@@QAE@XZ			; CTextureManager::~CTextureManager
EXTRN	_strcmp:PROC
EXTRN	_D3DX10CreateShaderResourceViewFromFileA@24:PROC
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\simon\documents\github\game-of-life\texturemanager.cpp
;	COMDAT ??1CTextureManager@@QAE@XZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
??1CTextureManager@@QAE@XZ PROC				; CTextureManager::~CTextureManager, COMDAT
; _this$ = ecx

; 11   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 12   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
??1CTextureManager@@QAE@XZ ENDP				; CTextureManager::~CTextureManager
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\simon\documents\github\game-of-life\texturemanager.cpp
;	COMDAT ??0CTextureManager@@QAE@PAUID3D10Device@@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_device$ = 8						; size = 4
??0CTextureManager@@QAE@PAUID3D10Device@@@Z PROC	; CTextureManager::CTextureManager, COMDAT
; _this$ = ecx

; 5    : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 6    : 	mpd3dDevice = device;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _device$[ebp]
	mov	DWORD PTR [eax], ecx

; 7    : }

	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
??0CTextureManager@@QAE@PAUID3D10Device@@@Z ENDP	; CTextureManager::CTextureManager
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\simon\documents\github\game-of-life\texturemanager.cpp
;	COMDAT ?UnloadTexture@CTextureManager@@QAEXH@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_index$ = 8						; size = 4
?UnloadTexture@CTextureManager@@QAEXH@Z PROC		; CTextureManager::UnloadTexture, COMDAT
; _this$ = ecx

; 43   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 44   : 
; 45   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
?UnloadTexture@CTextureManager@@QAEXH@Z ENDP		; CTextureManager::UnloadTexture
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\simon\documents\github\game-of-life\texturemanager.cpp
;	COMDAT ?UnloadTexture@CTextureManager@@QAEXQAD@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_filename$ = 8						; size = 4
?UnloadTexture@CTextureManager@@QAEXQAD@Z PROC		; CTextureManager::UnloadTexture, COMDAT
; _this$ = ecx

; 38   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 39   : 
; 40   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
?UnloadTexture@CTextureManager@@QAEXQAD@Z ENDP		; CTextureManager::UnloadTexture
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\simon\documents\github\game-of-life\texturemanager.cpp
;	COMDAT ?LoadTexture@CTextureManager@@QAEPAUID3D10ShaderResourceView@@QAD@Z
_TEXT	SEGMENT
_newTexture$ = -32					; size = 4
_i$1 = -20						; size = 4
_this$ = -8						; size = 4
_filename$ = 8						; size = 4
?LoadTexture@CTextureManager@@QAEPAUID3D10ShaderResourceView@@QAD@Z PROC ; CTextureManager::LoadTexture, COMDAT
; _this$ = ecx

; 15   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 228				; 000000e4H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-228]
	mov	ecx, 57					; 00000039H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 16   : 	
; 17   : 	for( int i = 0; i < miNumTextures; i++ )

	mov	DWORD PTR _i$1[ebp], 0
	jmp	SHORT $LN5@LoadTextur
$LN4@LoadTextur:
	mov	eax, DWORD PTR _i$1[ebp]
	add	eax, 1
	mov	DWORD PTR _i$1[ebp], eax
$LN5@LoadTextur:
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _i$1[ebp]
	cmp	ecx, DWORD PTR [eax+5404]
	jge	SHORT $LN3@LoadTextur

; 18   : 	{
; 19   : 		if( strcmp( filename, mcTexturesFile[i] ) == 0 )

	imul	eax, DWORD PTR _i$1[ebp], 50
	mov	ecx, DWORD PTR _this$[ebp]
	lea	edx, DWORD PTR [ecx+eax+404]
	push	edx
	mov	eax, DWORD PTR _filename$[ebp]
	push	eax
	call	_strcmp
	add	esp, 8
	test	eax, eax
	jne	SHORT $LN2@LoadTextur

; 20   : 		{
; 21   : 			return mpTextures[i];

	mov	eax, DWORD PTR _i$1[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [ecx+eax*4+4]
	jmp	SHORT $LN6@LoadTextur
$LN2@LoadTextur:

; 22   : 		}
; 23   : 	}

	jmp	SHORT $LN4@LoadTextur
$LN3@LoadTextur:

; 24   : 	
; 25   : 	ID3D10ShaderResourceView* newTexture;
; 26   : 	D3DX10CreateShaderResourceViewFromFileA( mpd3dDevice, filename,		NULL, NULL, &newTexture, NULL );

	push	0
	lea	eax, DWORD PTR _newTexture$[ebp]
	push	eax
	push	0
	push	0
	mov	ecx, DWORD PTR _filename$[ebp]
	push	ecx
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx]
	push	eax
	call	_D3DX10CreateShaderResourceViewFromFileA@24

; 27   : 	if( newTexture == nullptr )

	cmp	DWORD PTR _newTexture$[ebp], 0
	jne	SHORT $LN1@LoadTextur

; 28   : 	{
; 29   : 		return nullptr;

	xor	eax, eax
	jmp	SHORT $LN6@LoadTextur
$LN1@LoadTextur:

; 30   : 	}
; 31   : 
; 32   : 	mpTextures[miNumTextures] = newTexture;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+5404]
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR _newTexture$[ebp]
	mov	DWORD PTR [edx+ecx*4+4], eax

; 33   : 	miNumTextures++;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+5404]
	add	ecx, 1
	mov	edx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [edx+5404], ecx
$LN6@LoadTextur:

; 34   : 	
; 35   : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN10@LoadTextur
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 228				; 000000e4H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
	npad	2
$LN10@LoadTextur:
	DD	1
	DD	$LN9@LoadTextur
$LN9@LoadTextur:
	DD	-32					; ffffffe0H
	DD	4
	DD	$LN8@LoadTextur
$LN8@LoadTextur:
	DB	110					; 0000006eH
	DB	101					; 00000065H
	DB	119					; 00000077H
	DB	84					; 00000054H
	DB	101					; 00000065H
	DB	120					; 00000078H
	DB	116					; 00000074H
	DB	117					; 00000075H
	DB	114					; 00000072H
	DB	101					; 00000065H
	DB	0
?LoadTexture@CTextureManager@@QAEPAUID3D10ShaderResourceView@@QAD@Z ENDP ; CTextureManager::LoadTexture
_TEXT	ENDS
END
